### ISSUE TITLE
Add Synthetics API

### ISSUE THREAD

**Issue by bouktin** [sansible/newrelic-api#17]
Add the Synthetics API as described in:
https://docs.newrelic.com/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api

```
curl -v \
     -H 'X-Api-Key:{Admin_User_Key}' https://synthetics.newrelic.com/synthetics/api/v3/monitors
```

**Comment by lobsterdore** [comment]
This should be done on the main Ambitionic repo, closing for now.
