### ISSUE TITLE
Add EU Endpoints integration

### ISSUE THREAD

**Issue by bouktin** [sansible/newrelic-api#18]
For accounts created in the EU region, the API requires specific endpoints.
https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/getting-started/introduction-eu-region-data-center

**Comment by lobsterdore** [comment]
Thanks @bouktin, are you able to make these changes yourself at all for this issue and https://github.com/sansible/newrelic-api/issues/17? It will probably be some time before I am able to work on these issues.

**Comment by bouktin** [comment]
Hey @lobsterdore, I apologize, I meant to update the tickets. But yes, I'm working on both issues.  Is there a way you can add me to the repo so that I can create pull requests and grab issues?

Thanks, Thomas

**Comment by lobsterdore** [comment]
Great stuff, thanks very much! You can open pulls if you fork this repo, I've assigned this and the other issue to you.

**Comment by lobsterdore** [comment]
This should be done on the main Ambitionic repo, closing for now.
