### ISSUE TITLE
Contribute back to original project or take over the PyPi newrelic-api project

### ISSUE THREAD

**Issue by bouktin** [sansible/newrelic-api#19]
Find an agreement with the owner of newrelic-api on PyPi (https://pypi.org/project/newrelic-api/) to publish updates from this fork over there.

In case the original @ambitioninc user is not reachable, here's the procedure to take over the project.
https://www.python.org/dev/peps/pep-0541/#continued-maintenance-of-an-abandoned-project

Thomas

**Comment by lobsterdore** [comment]
Yes I agree @bouktin, I will reach to @ambitioninc to see if he will merge our updates in.

**Comment by lobsterdore** [comment]
We managed to ping some code back to the main project, closing for now.
